BENCHMARK_CHOICE_DATASET_IDX = 5

BENCHMARK_CHECK_PROTOCOL_CORRECTNESS=False

BENCHMARK_MEASURE_OFFLINE_COMMU=False

BENCHMARK_MEASURE_ONLINE_COMMU=False

BENCHMARK_MEASURE_ONLINE_COMPUTATION=True

BENCHMARK_OVER_CLOUD=True

# BENCHMARK_OVER_SIMULATED=True

######Performance improvement options##########
# PERFORMANCE_BATCH_SIZE = 2200
# PERFORMANCE_BATCH_SIZE = 1400
PERFORMANCE_BATCH_SIZE = 700
######Performance improvement options##########